horizonpwr-rails/config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :referrals
  resources :incoming_webhooks
  resources :calendar_notes
  get "/calendar_feed/:id", to: "calendars#feed", as: "calendar_feed"
  resources :applicants, only: [:new, :create]
  resources :careers, only: [:index, :show]
  post "canvass/note"
  post "canvass/appointment"
  post "canvass/interaction"
  draw :turbo
  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        require "sidekiq/cron/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users
      namespace :user do
        # resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      # resources :plans
      # namespace :pay do
      #   resources :charges
      #   resources :subscriptions
      # end

      root to: "dashboard#show"
    end
  end
  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :uploads
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      masquerades: "jumpstart/masquerades",
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts, except: :destroy do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members do
      get :deactivate
    end
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :pause
    patch :resume
  end
  resources :charges

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  get :mark_non_feedback_notifications_as_read, controller: :notifications
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :analytics
    get :refresh_project_csv
    get :code_snippets
    get :terms
    get :contest
    get :podcast
    get :leaderboard
    get :installers_leaderboard
    get :onboarding
    get :privacy
    get :pricing
    get :roadmap
    get :gitbook
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "static#leaderboard", as: :user_root
  end

  authenticate :user do
    get "/edit_attachments", to: "attachments#index"
    delete "/remove_attachment", to: "attachments#destroy"
    resources :calendars
    resources :concessions
    # resources :contests # Fix `rails test test/controllers/contests_controller_test.rb` before taking this live.
    resources :fundings, only: [:index]
    post "/add_to_aurora", to: "aurora#add_to_aurora"
    post "/deactivate_aurora", to: "aurora#deactivate_aurora"
    post "/reactivate_aurora", to: "aurora#reactivate_aurora"
    post "/add_to_canvass", to: "canvass#add_to_canvass"
    post "/deactivate_canvass", to: "canvass#deactivate_canvass"
    post "/reactivate_canvass", to: "canvass#reactivate_canvass"
    post "/onboard_user", to: "users#onboard_user"
    post "/subscribe_to_note", to: "notes#subscribe_to_note"
    post "/unsubscribe_from_note", to: "notes#unsubscribe_from_note"
    post "/update_task_completion", to: "appointments#update_task_completion"
    post "/appointment_failed", to: "appointments#mark_failed"

    resources :applicants do
      get :invite
    end
    resources :departments
    resources :note_tags, only: [:create]
    post "delete_tag", to: "note_tags#destroy"
    resources :notes
    resources :events
    resources :earning_rates, except: [:destroy, :new]
    get "/earnings/new", to: "errors#not_found"
    resources :earnings, except: [:new, :create, :destroy] do
      resources :adjustments
    end
    resources :payout_rate_variants, except: [:destroy, :new]
    resources :adjustments
    resources :payouts, except: :destroy
    resources :earning_types, except: :destroy
    resources :upline_relations
    resources :finance_partners
    resources :feedbacks do
      get :vote
      get :create_tracker_story
    end
    resources :field_responses, except: [:new]
    resources :form_responses, except: [:new]
    resources :dynamic_forms
    resources :field_configs
    resources :form_configs
    resources :user_filters, except: [:show, :index, :edit]
    resources :users do
      get "/onboarding_complete", to: "users#onboarding_complete"
      resources :documents
      resources :pending_job_positions
    end
    # TODO: `except: :destroy` isn't quite working the way we expect it to.
    resources :teams, except: :destroy, controller: "accounts", as: "teams"
    resources :proposals do
      resources :attachment_tags
      resources :energy_consumptions, except: [:index, :show]
      get :blocked
      get :unblocked
      get :back
      get :start_design
      get :end_design
      get :start_quality
      get :unstart_quality
      get :quality_progress
      post :quality_progress
      post :quality_previous
      get :end_quality
      get :create_aurora_project, controller: :aurora
      get :request_aurora_3dms, controller: :aurora
      get :validate_project
    end
    resources :contact_addresses
    resources :contact_appointments
    resources :projects do
      get :link_salesforce
      resources :concessions
      resources :attachment_tags
      resources :fundings do
        resources :funding_payments, except: [:show]
      end
    end
    resources :job_positions, except: :destroy
    resources :installers
    resources :addresses
    resources :appointments, except: :new do
      put "appointment_held", to: "appointments#update_held"
      get :selected_appointment
    end
    resources :contacts
    post "invite_installer", to: "installer_invites#toggle"
    post "reply_to_note", to: "note_replies#create"
    # root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

horizonpwr-rails/app/views/shared/_account_navbar.html.erb
<div class="bg-white border border-gray-300 rounded-lg">
  <%= nav_link_to t(".profile"), edit_user_registration_path, class: "block no-underline p-3 px-6 rounded-t", active_class: "bg-primary-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
  <%= nav_link_to t(".password"), edit_account_password_path, class: "block no-underline p-3 px-6", active_class: "bg-primary-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
  <%= nav_link_to t(".connected_accounts"), user_connected_accounts_path, class: "block no-underline p-3 px-6", active_class: "bg-primary-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" if Devise.omniauth_configs.any? %>
  <% unless turbo_native_app? %>
    <%#= nav_link_to t(".billing"), subscription_path, class: "block no-underline p-3 px-6", active_class: "bg-primary-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: ["/subscription", "/card"] if Jumpstart.config.payments_enabled? %>
  <% end %>
  <%#= nav_link_to t(".accounts"), accounts_path, class: "block no-underline p-3 px-6", active_class: "bg-primary-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: "/accounts" %>
  <%= nav_link_to "Documents", user_documents_path(current_user), class: "block no-underline p-3 px-6", active_class: "bg-primary-600 text-white hover:text-white rounded-b-lg", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100" %>
  <%#= nav_link_to t(".api_tokens"), api_tokens_path, class: "block no-underline p-3 px-6 rounded-b", active_class: "bg-primary-600 text-white hover:text-white", inactive_class: "text-gray-700 hover:text-gray-700 hover:bg-gray-100", starts_with: "/api_tokens" %>
</div>

horizonpwr-rails/app/views/shared/_account_profile.html.erb
<div class="flex items-left">
  <div class="flex-shrink-0 h-10 w-10">
    <%= image_tag avatar_url_for(account), class: "h-10 inline-block rounded-full mr-2" %>
  </div>
  <div class="ml-4">
    <div class="flex w-full justify-center space-x-3 items-center">
      <div class="w-full">
        <%= link_to account.name, account_path(account), class: "text-m text-gray-900" %>
      </div>
    </div>
    <div class="text-sm text-gray-500">
      <%= link_to 'manage', account_path(account), class: 'text-gray-500 text-sm' if allowed_to?(:manage?, account) %>
    </div>
  </div>
</div>

horizonpwr-rails/app/views/shared/_arrows.html.erb
<span class="relative z-0 inline-flex shadow-sm rounded-md">
  <%= link_to link_previous, class: "relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500" do %>
    <span class="sr-only">Previous</span>
    <!-- Heroicon name: solid/chevron-left -->
    <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"/>
    </svg>
  <% end %>
  <%= link_to link_next, class: "-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500" do %>
    <span class="sr-only">Next</span>
    <!-- Heroicon name: solid/chevron-right -->
    <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
    </svg>
    <% end %>
</span>

horizonpwr-rails/app/views/shared/_flash.html.erb
<div id="flash">
  <% if notice && notice&.present? %>
    <div class="notice notice-info flex items-center bg-blue-100 text-blue-600 justify-center text-sm font-bold px-4 py-3" role="alert">
      <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
      <p><%= sanitize notice.to_s %></p>
    </div>
  <% end %>

  <% if alert %>
    <div class="notice notice-warning items-center bg-red-100 text-red-600 justify-center text-sm font-bold px-4 py-3" role="alert">
      <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
      <p><%= sanitize alert %></p>
    </div>
  <% end %>

  <% if Jumpstart.config.stripe? && user_signed_in? && current_account&.has_incomplete_payment? %>
    <div class="notice notice-warning" role="alert">
      <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
      <p><%= link_to t(".confirm_payment"), pay.payment_path(current_account.subscription.latest_payment.id) %></p>
    </div>
  <% end %>
</div>

horizonpwr-rails/app/views/shared/_footer.html.erb
<div class="w-full h-auto px-2 py-4 text-sm lg:px-6">
  <div class="flex flex-col-reverse p-4 text-sm lg:flex-row lg:justify-between lg:p-0">
    <div class="flex items-center justify-center">
      <%= link_to root_path, class: "hidden sm:inline-block" do %>
        <%= image_tag('logo-horizonpwr.png', class: "h-8") %>
      <% end %>
      <div class="ml-4 text-gray-700">© <%= Date.current.year %> <%= Jumpstart.config.business_name %></div>
    </div>

    <div class="flex flex-wrap justify-center">
      <%= link_to "Snippets", code_snippets_path, class: "text-gray-700 no-underline block px-4 lg:my-0 my-2" if user_signed_in? && current_user.admin? %>
      <%= link_to "Careers", careers_path, class: 'text-gray-700 no-underline block px-4 lg:my-0 my-2 font-bold' unless active_user_signed_in? %>
      <%= link_to "Feedback", feedbacks_path, class: "text-gray-700 no-underline block px-4 lg:my-0 my-2 font-bold" if user_signed_in? %>
      <%= link_to t(".about"), about_path, class: "text-gray-700 no-underline block px-4 lg:my-0 my-2" %>
      <%= link_to t(".privacy"), privacy_path, class: "text-gray-700 hover:text-gray-800 no-underline block lg:my-0 my-2 px-4" %>
      <%= link_to t(".terms"), terms_path, class: "text-gray-700 hover:text-gray-800 no-underline block lg:my-0 my-2 px-4" %>
    </div>
  </div>
</div>

horizonpwr-rails/app/views/shared/_fullstory_footer.html.erb
<% if ['production', 'staging'].include?(Rails.env) %>
  <% if !current_user&.admin? %>
    <script>
      <% if user_signed_in? && current_account %>
      FS.identify("<%= current_user.id %>", {
        displayName: "<%= current_user.name %>",
        // TODO: Add your own custom user variables here, details at
        // https://help.fullstory.com/hc/en-us/articles/360020623294
        JobPosition: "<%= current_user&.job_position&.name %>",
        email: "<%= current_user.email %>",
        user_str: "<%= admin_user_url(current_user) %>",
        account_str: "<%= admin_account_url(current_account) %>",
        Leadership: "<%= current_user.job_position&.leadership %>",
        Canvass: "<%= current_user.canvass_user_id %>",
        Accounts: "<%= current_user.accounts.impersonal.map(&:name).uniq %>",
        Phone: "<%= current_user.phone %>",
        Active: "<%= current_user.active %>",
        Admin: "<%= current_user.admin %>",
        UserLink: "<%= user_url(current_user) %>",
      });
      <% end %>
    </script>
  <% end %>
<% end %>

horizonpwr-rails/app/views/shared/_hotjar.html.erb
<% if ['production', 'staging'].include?(Rails.env) %>
<!-- Hotjar Tracking Code for My site -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2729578,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

  <% if user_signed_in? %>
  <!-- Install this snippet AFTER the Hotjar tracking code. -->
    <script>
        var userId = <%= current_user.id %> || null; // Replace your_user_id with your own if available.
        window.hj('identify', userId, {
            'Start Date': '<%= current_user.start_date %>',
            'Name': '<%= current_user.name %>',
            'Job Position': '<%= current_user.job_position&.name %>',
            'Leadership': '<%= current_user.job_position&.leadership %>',
            'Email': '<%= current_user.email %>',
            'Canvass': '<%= current_user.canvass_user_id %>',
            'Accounts': '<%= current_user.accounts.impersonal.map(&:name).uniq %>',
            'Phone': '<%= current_user.phone %>',
            'Active': '<%= current_user.active %>',
            'Admin': '<%= current_user.admin %>',
            'UserLink': '<%= user_url(current_user) %>',
            // Add your own custom attributes here. Some EXAMPLES:
            // 'Signed up': '2019—06-20Z', // Signup date in ISO-8601 format.
            // 'Last purchase category': 'Electronics', // Send strings with quotes around them.
            // 'Total purchases': 15, // Send numbers without quotes.
            // 'Last purchase date': '2019-06-20Z', // Send dates in ISO-8601 format.
            // 'Last refund date': null, // Send null when no value exists for a user.
        });
    </script>
  <% end %>
<% end %>

horizonpwr-rails/app/views/shared/_installers_leaderboard_teams.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div id="teams-card" class="flex flex-col">
  <div class="my-2 overflow-x-auto">
    <div class=" rounded-lg overflow-hidden shadow-lg bg-white">
      <div class="rounded-tl-lg rounded-tr-lg sm:rounded-tr-none relative group bg-white p-6 focus-within:ring-2 focus-within:ring-inset focus-within:ring-cyan-500 overflow-x-auto">
        <p class="w-full text-center">
          Week of April 1, 2022
        </p>
        <%= form_tag(installers_leaderboard_path(time_period: params[:time_period], end_at: params[:end_at]), method: :get, class: 'flex items-center mb-6') do %>
          <div class="w-full">
            <%= select_tag :time_period,
                           options_for_select(PerformanceStat.time_period_options, params[:time_period]),
                           { allow_blank: false, class: "mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" }
            %>
          </div>
          <%= submit_tag 'apply', class: "btn btn-primary inline-flex mx-4" %>
          <%= render partial: 'shared/arrows', locals: {
            link_previous: installers_leaderboard_path(PerformanceStat.link_previous_params(params[:end_at], params[:time_period])),
            link_next: installers_leaderboard_path(PerformanceStat.link_next_params(params[:end_at], params[:time_period]))
          } %>
        <% end %>
        <table class="w-full">
          <span class="text-gray-900 font-bold text-lg">Installers</span>

          <thead>
          <tr class="text-left">
            <th class="p-3 text-xs text-left text-gray-600 uppercase">

            </th>
            <th class="p-3 text-xs text-left text-gray-600 uppercase">

            </th>
            <th class="p-3 text-xs text-left text-gray-600 uppercase text-center">
              KW
            </th>
            <th class="p-3 text-xs text-left text-gray-600 uppercase text-center">
              Pass Rate
            </th>
            <th class="p-3 text-xs text-left text-gray-600 uppercase text-center">
              PWR Ranking
            </th>
          </tr>
          </thead>
          <tbody class="bg-white">
          <% @teams.each_with_index do |team, index| %>
            <tr class="border-b border-gray-400 group bg-white hover:bg-gray-200 text-center">
              <td class="py-4 whitespace-nowrap">
                <!--             Leaderboard Position Number-->
                <p class="text-lg text-blue-500 font-bold"><%= (index + 1).ordinalize %></p>
              </td>
              <td class="py-4 whitespace-nowrap">
                <div class="text-sm font-medium text-gray-900">
                  <%= link_to team.name, leaderboard_path(:team => team.name), class: 'text-gray-900' %>
                  <br/>
                  <%= link_to 'manage', team_path(team), class: 'text-gray-500 text-sm' if allowed_to?(:manage?, team) %>
                </div>
              </td>
              <td class="px-3 py-4 whitespace-nowrap">
                15
              </td>
              <td class="px-3 py-4 whitespace-nowrap">
                20%
              </td>
              <td class="px-3 py-4 whitespace-nowrap">
                <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-green-100 text-green-800">
                 50pts
              </span>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

horizonpwr-rails/app/views/shared/_left_nav.html.erb
<%= nav_link_to "Leaderboard", leaderboard_path, class: 'nav-link-mobile' %>
<%= nav_link_to "Members", users_path, class: 'nav-link-mobile' %>
<%= nav_link_to "Addresses", addresses_path, class: 'nav-link-mobile'  if allowed_to?(:index?, Address, with: AddressPolicy) %>
<%= nav_link_to "Analytics", analytics_path, class: 'nav-link-mobile' if allowed_to?(:manage?, Proposal, with: ProposalPolicy ) %>
<%= nav_link_to "Appointments", appointments_path, class: 'nav-link-mobile' if allowed_to?(:index?, Appointment, with: AppointmentPolicy) %>
<%= nav_link_to "Calendar", calendars_path, class: 'nav-link-mobile' if allowed_to?(:index?, Calendar, with: CalendarPolicy ) %>
<%= nav_link_to "Contacts", contacts_path, class: 'nav-link-mobile' %>
<%= nav_link_to "Departments", departments_path, class: 'nav-link-mobile' if allowed_to?(:index?, Department, with: DepartmentPolicy ) %>
<%= nav_link_to "Fundings", fundings_path, class: 'nav-link-mobile' if allowed_to?(:index?, Funding, with: FundingPolicy ) %>
<%#= nav_link_to "Funding Payments", funding_payments_path, class: 'nav-link-mobile' if allowed_to?(:index?, FundingPayment, with: FundingPaymentPolicy ) %>
<%= nav_link_to "Onboarding", applicants_path, class: 'nav-link-mobile' if allowed_to?(:index?, Applicant, with: ApplicantPolicy ) %>
<%= nav_link_to "Payouts", payouts_path, class: 'nav-link-mobile' if allowed_to?(:index?, Payout, with: PayoutPolicy ) %>
<%= nav_link_to "Podcast", podcast_path, class: 'nav-link-mobile' %>
<%= nav_link_to "Projects", projects_path, class: 'nav-link-mobile' if allowed_to?(:index?, Project, with: ProjectPolicy) %>
<%= nav_link_to "Proposals", proposals_path, class: 'nav-link-mobile' if allowed_to?(:index?, Proposal, with: ProposalPolicy) %>
<%#= nav_link_to "Calendar Notes", calendar_notes_path, class: 'nav-link-mobile' if allowed_to?(:index?, CalendarNote, with: CalendarNotePolicy ) %>
<%#= nav_link_to "User Filters", user_filters_path, class: 'nav-link-mobile' if allowed_to?(:index?, UserFilter, with: UserFilterPolicy ) %>
<%#= nav_link_to "Contests", contests_path, class: 'nav-link-mobile' if allowed_to?(:index?, Contest, with: ContestPolicy ) %>
<%= nav_link_to "Referrals", referrals_path, class: 'nav-link-mobile' if allowed_to?(:index?, Referral, with: ReferralPolicy ) %>
<%= nav_link_to "Training", gitbook_path, class: 'nav-link-mobile' %>

horizonpwr-rails/app/views/shared/_right_nav.html.erb
<%# Place any links for the RIGHT side of the nav bar here. Be sure to add class: "nav-link" to each item for proper spacing. %>

<% if Jumpstart.config.payments_enabled? && (!user_signed_in? || current_account_admin?) && not_subscribed? %>
  <%= nav_link_to t(".pricing"), pricing_path, class: "nav-link" %>
<% end %>

<% if user_signed_in? && current_user.active? %>
  <%= nav_link_to tag.span(t(".announcements")), announcements_path, class: ["nav-link hidden xl:block", unread_announcements_class(current_user)] %>
<% end %>

horizonpwr-rails/app/views/shared/_status_color.html.erb
<div class="flex items-center">
  <div class="h-2 w-2 bg-<%= object.status_color %>-400 rounded-full mr-1">
  </div>
  <div class="text-sm capitalize font-bold leading-normal text-<%= object.status_color %>-500">
    <%= object.status %>
  </div>
</div>

horizonpwr-rails/app/views/shared/_user_profile.html.erb
<%= image_tag avatar_url_for(user, size: 150), class: "mx-auto h-24 w-24 rounded-full" %>
<div class="space-y-2">
  <div class="text-xs font-medium lg:text-sm">
    <p>
      <%= user.name %>
    </p>
    <p class="text-yellow-600 font-medium">
      <%= user.job_position_name %>
    </p>
  </div>
</div>