horizonpwr-rails/config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :referrals
  resources :incoming_webhooks
  resources :calendar_notes
  get "/calendar_feed/:id", to: "calendars#feed", as: "calendar_feed"
  resources :applicants, only: [:new, :create]
  resources :careers, only: [:index, :show]
  post "canvass/note"
  post "canvass/appointment"
  post "canvass/interaction"
  draw :turbo
  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        require "sidekiq/cron/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users
      namespace :user do
        # resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      # resources :plans
      # namespace :pay do
      #   resources :charges
      #   resources :subscriptions
      # end

      root to: "dashboard#show"
    end
  end
  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :uploads
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      masquerades: "jumpstart/masquerades",
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts, except: :destroy do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members do
      get :deactivate
    end
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :pause
    patch :resume
  end
  resources :charges

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  get :mark_non_feedback_notifications_as_read, controller: :notifications
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :analytics
    get :refresh_project_csv
    get :code_snippets
    get :terms
    get :contest
    get :podcast
    get :leaderboard
    get :installers_leaderboard
    get :onboarding
    get :privacy
    get :pricing
    get :roadmap
    get :gitbook
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "static#leaderboard", as: :user_root
  end

  authenticate :user do
    get "/edit_attachments", to: "attachments#index"
    delete "/remove_attachment", to: "attachments#destroy"
    resources :calendars
    resources :concessions
    # resources :contests # Fix `rails test test/controllers/contests_controller_test.rb` before taking this live.
    resources :fundings, only: [:index]
    post "/add_to_aurora", to: "aurora#add_to_aurora"
    post "/deactivate_aurora", to: "aurora#deactivate_aurora"
    post "/reactivate_aurora", to: "aurora#reactivate_aurora"
    post "/add_to_canvass", to: "canvass#add_to_canvass"
    post "/deactivate_canvass", to: "canvass#deactivate_canvass"
    post "/reactivate_canvass", to: "canvass#reactivate_canvass"
    post "/onboard_user", to: "users#onboard_user"
    post "/subscribe_to_note", to: "notes#subscribe_to_note"
    post "/unsubscribe_from_note", to: "notes#unsubscribe_from_note"
    post "/update_task_completion", to: "appointments#update_task_completion"
    post "/appointment_failed", to: "appointments#mark_failed"

    resources :applicants do
      get :invite
    end
    resources :departments
    resources :note_tags, only: [:create]
    post "delete_tag", to: "note_tags#destroy"
    resources :notes
    resources :events
    resources :earning_rates, except: [:destroy, :new]
    get "/earnings/new", to: "errors#not_found"
    resources :earnings, except: [:new, :create, :destroy] do
      resources :adjustments
    end
    resources :payout_rate_variants, except: [:destroy, :new]
    resources :adjustments
    resources :payouts, except: :destroy
    resources :earning_types, except: :destroy
    resources :upline_relations
    resources :finance_partners
    resources :feedbacks do
      get :vote
      get :create_tracker_story
    end
    resources :field_responses, except: [:new]
    resources :form_responses, except: [:new]
    resources :dynamic_forms
    resources :field_configs
    resources :form_configs
    resources :user_filters, except: [:show, :index, :edit]
    resources :users do
      get "/onboarding_complete", to: "users#onboarding_complete"
      resources :documents
      resources :pending_job_positions
    end
    # TODO: `except: :destroy` isn't quite working the way we expect it to.
    resources :teams, except: :destroy, controller: "accounts", as: "teams"
    resources :proposals do
      resources :attachment_tags
      resources :energy_consumptions, except: [:index, :show]
      get :blocked
      get :unblocked
      get :back
      get :start_design
      get :end_design
      get :start_quality
      get :unstart_quality
      get :quality_progress
      post :quality_progress
      post :quality_previous
      get :end_quality
      get :create_aurora_project, controller: :aurora
      get :request_aurora_3dms, controller: :aurora
      get :validate_project
    end
    resources :contact_addresses
    resources :contact_appointments
    resources :projects do
      get :link_salesforce
      resources :concessions
      resources :attachment_tags
      resources :fundings do
        resources :funding_payments, except: [:show]
      end
    end
    resources :job_positions, except: :destroy
    resources :installers
    resources :addresses
    resources :appointments, except: :new do
      put "appointment_held", to: "appointments#update_held"
      get :selected_appointment
    end
    resources :contacts
    post "invite_installer", to: "installer_invites#toggle"
    post "reply_to_note", to: "note_replies#create"
    # root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

horizonpwr-rails/app/controllers/careers_controller.rb
class CareersController < ApplicationController
  before_action :set_job_position, only: [:show, :edit, :update, :destroy]

  # GET /job_positions
  def index
    @pagy, @careers = pagy(JobPosition.currently_hiring.sort_by_params(params[:sort], sort_direction))

    # We explicitly load the records to avoid triggering multiple DB calls in the views when checking if records exist and iterating over them.
    # Calling @careers.any? in the view will use the loaded records to check existence instead of making an extra DB call.
    @careers.load
  end

  # GET /job_positions/1
  def show
    @users = @career.users.where(active: true).with_attached_avatar
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job_position
    @career = JobPosition.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def job_position_params
    params.require(:job_position).permit(:name, :active)
  end
end

horizonpwr-rails/app/helpers/careers_helper.rb
module CareersHelper
end

horizonpwr-rails/app/views/careers/_filter.html.erb
<!-- filters -->
<div class="flex pt-3 pb-3" data-controller="onClick">
  <div data-onClick-target="leftButton" class="hidden" data-action="click->onClick#scrollLeft">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
    </svg>
  </div>
  <div data-controller="onScroll" data-onClick-target="filtersContainer" data-action="scroll->onScroll#scrollMove" class="whitespace-nowrap overflow-x-auto scrollbar-hide px-2 text-center">
    <%= link_to "All", careers_path(filter: 'all'), class:'mr-2 text-gray-700' %>
  </div>
  <div data-onClick-target="rightButton" class="" data-action="click->onClick#scrollRight">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
    </svg>
  </div>
</div>
<!-- end of filters -->

horizonpwr-rails/app/views/careers/_form.html.erb
<%= form_with(model: career) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="flex justify-between form-group">
    <%= form.button class: "btn btn-primary" %>

    <% if form.object.persisted? && allowed_to?(:destroy?, form.object)%>
      <%= link_to t("delete"), form.object, class: "btn btn-danger outline", method: :delete, data: { confirm: t("are_you_sure") } %>
    <% end %>
  </div>
<% end %>

horizonpwr-rails/app/views/careers/_header.html.erb
<!-- Header Card -->
<div class="flex flex-wrap bg-transparent sm:rounded-md">
    <!-- Header card contents  -->
    <div class="bg-white w-full mb-1 sm:mb-2 sm:rounded-t-md shadow-md p-6">
        <div class="flex flex-row justify-between">
            <div class="inline-flex items-center w-full h-9">
                <%= image_tag "mark.png", height: 20, width: 20, class: "w-9 h-full rounded-lg mr-4" %>
                <div class="inline-flex flex-col items-start h-full">
                    <div class="w-full mt-1 text-md font-semibold leading-none text-gray-900">
                        User Name
                      <%= link_to t("edit"), '#', class: "btn btn-link" %>
                    </div>
                    <div class="w-full mt-1 text-xs leading-3 text-gray-400">
                        Team Name
                    </div>
                </div>
            </div>
          <%= render 'shared/active_status_color', object: @career %>
        </div>
        <div class="flex flex-col mt-2 text-md">

            <div class="flex flex-row justify-between">
                <p>
                    Name: <%= @career.name %>
                </p>
                <p>
                </p>
            </div>
        </div>
    </div>
    <!-- End of Header card contents  -->
    <% if show_cards == true %>
        <!-- Card 1 contents  -->
        <div class="w-full sm:w-1/2 lg:w-1/4 pb-1 sm:pb-2 sm:pr-1 lg:pb-0 rounded-md">
            <div class="bg-white sm:rounded-r-lg lg:rounded-tr-lg lg:rounded-br-none lg:rounded-bl-md h-full shadow-lg">
                <div class="flex-col py-4 px-6">
                    <p class="mt-1 font-semibold leading-3 text-gray-900">Job Position</p>
                    <div class="inline-flex items-center mt-1">
                        <%= image_tag "mark.png", height: 20, width: 20, class: "w-9 h-full rounded-lg mr-4" %>
                        <div class="inline-flex flex-col justify-center">
                            <p class="text-sm font-semibold leading-none text-gray-900">User Name</p>
                            <p class="text-xs leading-3 text-gray-400 mt-1">Team Name</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End of card 1 contents  -->
        <!-- Card 2 contents  -->
        <div class="w-full sm:w-1/2 lg:w-1/4 pb-1 sm:pb-2 sm:pl-1 lg:pr-1 lg:pb-0">
            <div class="bg-white sm:rounded-l-lg lg:rounded-b-none lg:rounded-t-lg h-full shadow-lg">
                <div class="flex-col py-4 px-6">
                    <p class="mt-1 font-semibold leading-3 text-gray-900">Job Position</p>
                    <div class="inline-flex items-center mt-1">
                        <%= image_tag "mark.png", height: 20, width: 20, class: "w-9 h-full rounded-lg mr-4" %>
                        <div class="inline-flex flex-col justify-center">
                            <p class="text-sm font-semibold leading-none text-gray-900">User Name</p>
                            <p class="text-xs leading-3 text-gray-400 mt-1">Team Name</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End of card 2 contents  -->
        <!-- Card 3 contents  -->
        <div class="w-full sm:w-1/2 lg:w-1/4 pb-1 sm:pb-0 sm:pr-1 lg:pl-1">
            <div class="bg-white sm:rounded-tr-lg lg:rounded-t-lg h-full sm:rounded-bl-md lg:rounded-bl-none shadow-lg">
                <div class="flex-col py-4 px-6">
                    <p class="mt-1 font-semibold leading-3 text-gray-900">Job Position</p>
                    <div class="inline-flex items-center mt-1">
                        <%= image_tag "mark.png", height: 20, width: 20, class: "w-9 h-full rounded-lg mr-4" %>
                        <div class="inline-flex flex-col justify-center">
                            <p class="text-sm font-semibold leading-none text-gray-900">User Name</p>
                            <p class="text-xs leading-3 text-gray-400 mt-1">Team Name</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End of card 3 contents  -->
        <!-- Card 4 contents  -->
        <div class="w-full sm:w-1/2 lg:w-1/4 sm:pl-1 g">
            <div class="bg-white sm:rounded-tl-lg h-full lg:rounded-br-md sm:rounded-br-md lg:rounded-bl-none sm:rounded-bl-none shadow-lg">
                <div class="flex-col py-4 px-6">
                    <p class="mt-1 font-semibold leading-3 text-gray-900">Job Position</p>
                    <div class="inline-flex items-center mt-1">
                        <%= image_tag "mark.png", height: 20, width: 20, class: "w-9 h-full rounded-lg mr-4" %>
                        <div class="inline-flex flex-col justify-center">
                            <p class="text-sm font-semibold leading-none text-gray-900">User Name</p>
                            <p class="text-xs leading-3 text-gray-400 mt-1">Team Name</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End of card 4 contents  -->
    <% end %>
</div>
<!-- End of Header Card -->

horizonpwr-rails/app/views/careers/_search.html.erb
<div class="flex w-full shadow-lg rounded-md">
  <div class="w-3/4">
    <form action="/careers" accept-charset="UTF-8" method="get">
      <div class="relative">
        <input class="transition placeholder-gray-700 rounded-l-md border-r-0 border-gray-300 bg-white py-2 pr-4 pl-10 block w-full appearance-none leading-normal ds-input" placeholder="Search..." type="text" name="q" id="q" value="<%= params[:q] %>">
        <div class="pointer-events-none absolute inset-y-0 left-0 pl-4 flex items-center">
          <svg class="fill-current pointer-events-none text-gray-600 w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
          </svg>
        </div>
      </div>
    </form>
  </div>
  <div class="w-1/4">
    <%= render partial: "careers/sort" %>
  </div>
</div>

horizonpwr-rails/app/views/careers/_sort.html.erb
<div class="relative text-left" data-controller="dropdown" >
  <!-- sort dropdown -->
  <div data-action="click->dropdown#toggle click@window->dropdown#hide touch->dropdown#toggle touch@window->dropdown#hide" role="button" class="select-none relative rounded-l-none focus:outline-none rounded-r-md border-t border-b border-r border-gray-300 bg-white text-gray-700 hover:bg-gray-50" aria-label="Sort Menu">
    <p class="text-base leading-normal text-gray-500 absolute left-0 top-2">|</p>
    <div class="ml-1">
      <button type="button" class="inline-flex justify-center w-full p-2 hover:text-blue-500 focus:outline-none <%= 'font-semibold' if params[:sort].present? %>" id="menu-button" aria-expanded="true" aria-haspopup="true">
        sort
        <!-- Heroicon name: solid/chevron-down -->
        <svg class="h-5 w-5 pt-1 hover:text-blue-500 <%= 'font-semibold' if params[:sort].present? %>" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"/>
        </svg>
      </button>
    </div>
  </div>
  <!-- end of sort dropdown -->
  <!-- dropdown -->
  <div data-dropdown-target="menu" class="hidden origin-top-right absolute right-0 mt-2 w-36 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
    <div class="py-1" role="none">
              <div class="flex hover:bg-primary-100">
          <a href="#" class="text-gray-700 group flex items-center py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
            <%= sortable @careers, :name, "Name", class: "text-gray-700 mx-2 p-2 #{'font-semibold' if params[:sort].present? && params[:sort] == "name"}" %>
          </a>
        </div>
          </div>
  </div>
  <!-- end of dropdown -->
</div>

horizonpwr-rails/app/views/careers/edit.html.erb
<div class="container px-4 mx-auto my-8">
  <div class="max-w-3xl mx-auto">
    <div class="flex items-center justify-between mb-4">
      <h1 class="h3"><%= t("shared.scaffold.edit.title", model: "Career") %></h1>
      <%= link_to t("cancel"), @career, class: "btn btn-link" %>
    </div>

    <div class="p-8 bg-white rounded shadow">
      <%= render "form", career: @career %>
    </div>
  </div>
</div>

horizonpwr-rails/app/views/careers/index.html.erb
<div class="mx-auto my-4 px-1 md:px-2 lg:px-4">
  <div class="p-4 mt-10 pt-10 pb-10">
    <p class="text-6xl font-extrabold text-center text-gray-900">Become part of the Team</p>
    <br>
    <p class="text-lg font-medium text-center text-gray-500">Life is better lived when you positively impact others.</p>
    <p class="text-lg font-medium text-center text-gray-500">Join the purpose to brighten the horizons of those around us.</p>
  </div>
  <div class="flow-root lg:mb-4 <%= 'hidden' if !@careers.any? %>">
    <%#= link_to t("shared.scaffold.new.title", model: "Career"), '#{new_career_path}', class: "btn btn-primary float-right hidden lg:inline-block" %>
  </div>
  <div class="hidden flex-none flex-wrap-reverse lg:flex-wrap lg:flex items-center justify-between mb-4">
    <% if @careers.any? %>
      <div class="hidden w-full lg:w-1/4">
        <%= render partial: "careers/filter" %>
      </div>
      <div class="hidden w-full lg:w-1/4">
        <%= render partial: "careers/search" %>
      </div>
    <div class="w-full mt-2 text-center text-sm <%= 'hidden' if !params[:filter].present? %>">
      Filtered by: <%= "'#{params[:filter]}'" %>
    </div>
    <% end %>
  </div>
  <div class="bg-white rounded-lg">
    <% if @careers.any? %>
      <div class="table-responsive">
        <div class="p-6">
        <table class="table">
          <thead>
            <tr>
                <th class="p-3 hidden uppercase text-left text-xs"><%= sortable @careers, :name, "Name", class: "text-gray-700" %></th>
                <th class="p-3 uppercase hidden text-left text-xs text-gray-700 w-20"><%= t("shared.scaffold.actions") %></th>
            </tr>
          </thead>

          <tbody>
          <% @careers.each do |career| %>
            <tr class="group border-t border-gray-400 first:border-none">
                          <td class="p-2">
                            <%= career.name %>
                            <p class="text-sm text-gray-700">
                              <%= career.department&.name %>
                            </p>
                          </td>
              <td class="p-4 flex justify-end">
                <button type="button" class="px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  <%= link_to "More Details", career_path(career), class:'text-white hover:text-white'%>
                </button>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        </div>
        <%= render "shared/custom_pagy" %>
      </div>
    <% else %>
      <div class="bg-white rounded shadow flex flex-col items-center justify-between p-8 lg:flex-row">
        <%= image_tag "empty.svg", class: "mb-4 lg:w-1/2" %>
        <div class="flex-1 text-center">

        </div>
      </div>
    <% end %>
  </div>
</div>

horizonpwr-rails/app/views/careers/new.html.erb
<div class="container px-4 mx-auto my-8">
  <div class="max-w-3xl mx-auto">
    <div class="flex items-center justify-between mb-4">
      <h1 class="h3"><%= t("shared.scaffold.new.title", model: "Career") %></h1>
      <%= link_to t("cancel"), careers_path, class: "btn btn-link" %>
    </div>

    <div class="p-8 bg-white rounded shadow">
      <%= render "form", career: @career %>
    </div>
  </div>
</div>

horizonpwr-rails/app/views/careers/show.html.erb
<div class="my-8">
  <!-- Main 3 column grid -->
  <main class="mx-auto sm:px-6 lg:px-8">
    <!-- Main 3 column grid -->
    <div class="grid grid-cols-1 gap-4 lg:col-span-3">
      <nav class="flex mb-5" aria-label="Breadcrumb">
        <ol class="flex items-center">
          <li class="list-none">
            <div class="flex items-center">
              <!-- Heroicon name: solid/chevron-right -->
              <svg class="flex-shrink-0 h-5 w-5 text-gray-400 hidden" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
              </svg>
              <p class="text-xl font-bold mr-4 text-blue-500 hover:text-blue-700"><%= link_to "Careers", careers_path %></p>
            </div>
          </li>

          <li class="list-none">
            <div class="flex items-center">
              <!-- Heroicon name: solid/chevron-right -->
              <svg class="flex-shrink-0 h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
              </svg>
              <p class="ml-4 text-xl font-bold text-gray-500" aria-current="page">
                <%= @career.name %>
              </p>
            </div>
          </li>
        </ol>
        <div>
          <%= link_to 'Edit', edit_job_position_path(@career), class: "btn btn-link" %>
        </div>
      </nav>
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <div class="flex flex-row justify-between px-4 py-5 sm:px-6">
          <div class="">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
              <%= @career.name %>
            </h3>
            <p class="mt-1 max-w-2xl text-sm text-gray-500">
              <%= @career.department&.name %>
            </p>
          </div>
          <p class="btn btn-primary">
            <%= link_to "Apply Now", new_applicant_path(:jp => @career.id), class: "text-white hover:text-white" %>
          </p>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
          <p>
            <%= @career.description %>
          </p>
          <div class="w-full flex justify-end">
            <p class="btn btn-primary mt-4">
              <%= link_to "Apply Now", new_applicant_path(:jp => @career.id), class: "text-white hover:text-white" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>