horizonpwr-rails/config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :referrals
  resources :incoming_webhooks
  resources :calendar_notes
  get "/calendar_feed/:id", to: "calendars#feed", as: "calendar_feed"
  resources :applicants, only: [:new, :create]
  resources :careers, only: [:index, :show]
  post "canvass/note"
  post "canvass/appointment"
  post "canvass/interaction"
  draw :turbo
  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        require "sidekiq/cron/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users
      namespace :user do
        # resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      # resources :plans
      # namespace :pay do
      #   resources :charges
      #   resources :subscriptions
      # end

      root to: "dashboard#show"
    end
  end
  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :uploads
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      masquerades: "jumpstart/masquerades",
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts, except: :destroy do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members do
      get :deactivate
    end
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :pause
    patch :resume
  end
  resources :charges

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  get :mark_non_feedback_notifications_as_read, controller: :notifications
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :analytics
    get :refresh_project_csv
    get :code_snippets
    get :terms
    get :contest
    get :podcast
    get :leaderboard
    get :installers_leaderboard
    get :onboarding
    get :privacy
    get :pricing
    get :roadmap
    get :gitbook
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "static#leaderboard", as: :user_root
  end

  authenticate :user do
    get "/edit_attachments", to: "attachments#index"
    delete "/remove_attachment", to: "attachments#destroy"
    resources :calendars
    resources :concessions
    # resources :contests # Fix `rails test test/controllers/contests_controller_test.rb` before taking this live.
    resources :fundings, only: [:index]
    post "/add_to_aurora", to: "aurora#add_to_aurora"
    post "/deactivate_aurora", to: "aurora#deactivate_aurora"
    post "/reactivate_aurora", to: "aurora#reactivate_aurora"
    post "/add_to_canvass", to: "canvass#add_to_canvass"
    post "/deactivate_canvass", to: "canvass#deactivate_canvass"
    post "/reactivate_canvass", to: "canvass#reactivate_canvass"
    post "/onboard_user", to: "users#onboard_user"
    post "/subscribe_to_note", to: "notes#subscribe_to_note"
    post "/unsubscribe_from_note", to: "notes#unsubscribe_from_note"
    post "/update_task_completion", to: "appointments#update_task_completion"
    post "/appointment_failed", to: "appointments#mark_failed"

    resources :applicants do
      get :invite
    end
    resources :departments
    resources :note_tags, only: [:create]
    post "delete_tag", to: "note_tags#destroy"
    resources :notes
    resources :events
    resources :earning_rates, except: [:destroy, :new]
    get "/earnings/new", to: "errors#not_found"
    resources :earnings, except: [:new, :create, :destroy] do
      resources :adjustments
    end
    resources :payout_rate_variants, except: [:destroy, :new]
    resources :adjustments
    resources :payouts, except: :destroy
    resources :earning_types, except: :destroy
    resources :upline_relations
    resources :finance_partners
    resources :feedbacks do
      get :vote
      get :create_tracker_story
    end
    resources :field_responses, except: [:new]
    resources :form_responses, except: [:new]
    resources :dynamic_forms
    resources :field_configs
    resources :form_configs
    resources :user_filters, except: [:show, :index, :edit]
    resources :users do
      get "/onboarding_complete", to: "users#onboarding_complete"
      resources :documents
      resources :pending_job_positions
    end
    # TODO: `except: :destroy` isn't quite working the way we expect it to.
    resources :teams, except: :destroy, controller: "accounts", as: "teams"
    resources :proposals do
      resources :attachment_tags
      resources :energy_consumptions, except: [:index, :show]
      get :blocked
      get :unblocked
      get :back
      get :start_design
      get :end_design
      get :start_quality
      get :unstart_quality
      get :quality_progress
      post :quality_progress
      post :quality_previous
      get :end_quality
      get :create_aurora_project, controller: :aurora
      get :request_aurora_3dms, controller: :aurora
      get :validate_project
    end
    resources :contact_addresses
    resources :contact_appointments
    resources :projects do
      get :link_salesforce
      resources :concessions
      resources :attachment_tags
      resources :fundings do
        resources :funding_payments, except: [:show]
      end
    end
    resources :job_positions, except: :destroy
    resources :installers
    resources :addresses
    resources :appointments, except: :new do
      put "appointment_held", to: "appointments#update_held"
      get :selected_appointment
    end
    resources :contacts
    post "invite_installer", to: "installer_invites#toggle"
    post "reply_to_note", to: "note_replies#create"
    # root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

horizonpwr-rails/app/models/payout_rate_variant.rb
# == Schema Information
#
# Table name: payout_rate_variants
#
#  id              :bigint           not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  earning_rate_id :bigint           not null
#  earning_type_id :bigint           not null
#  payout_id       :bigint           not null
#
# Indexes
#
#  index_payout_rate_variants_on_earning_rate_id  (earning_rate_id)
#  index_payout_rate_variants_on_earning_type_id  (earning_type_id)
#  index_payout_rate_variants_on_payout_id        (payout_id)
#
# Foreign Keys
#
#  fk_rails_...  (earning_rate_id => earning_rates.id)
#  fk_rails_...  (earning_type_id => earning_types.id)
#  fk_rails_...  (payout_id => payouts.id)
#
class PayoutRateVariant < ApplicationRecord
  belongs_to :payout
  belongs_to :earning_rate
  belongs_to :earning_type
  has_many :earnings

  def initialize(attributes = {})
    super({payout: attributes[:payout],
           earning_type: attributes[:earning_type],
           earning_rate: EarningRate.find_by(earning_type: attributes[:earning_type])}) # This gets updated after_commit, just need a place holder here
    earnings << attributes[:earnings] if attributes[:earnings].present?
  end

  def find_earning_rate
    # If it's a new hire bonus, then the earning rate amount is either 0 or the total, nothing between
    quantity = payout.earning_type_count(earning_type)
    EarningRate.active.where("earning_type_id = ? and range_bottom <= ? and range_top >= ?", earning_type_id, quantity, quantity).first
  end

  def update_earning_rate
    update(earning_rate: find_earning_rate)
  end
end
# Earning.create!(unit: 1, address: Address.first, user: User.find(128))

horizonpwr-rails/app/controllers/payout_rate_variants_controller.rb
class PayoutRateVariantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payout_rate_variant, only: [:show, :edit, :update, :destroy]

  # GET /payout_rate_variants
  def index
    @pagy, @payout_rate_variants = pagy(PayoutRateVariant.sort_by_params(params[:sort], sort_direction))

    # We explicitly load the records to avoid triggering multiple DB calls in the views when checking if records exist and iterating over them.
    # Calling @payout_rate_variants.any? in the view will use the loaded records to check existence instead of making an extra DB call.
    @payout_rate_variants.load
  end

  # GET /payout_rate_variants/1
  def show
  end

  # GET /payout_rate_variants/new
  def new
    @payout_rate_variant = PayoutRateVariant.new
  end

  # GET /payout_rate_variants/1/edit
  def edit
  end

  # POST /payout_rate_variants
  def create
    @payout_rate_variant = PayoutRateVariant.new(payout_rate_variant_params)

    if @payout_rate_variant.save
      redirect_to @payout_rate_variant, notice: "Payout rate variant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /payout_rate_variants/1
  def update
    if @payout_rate_variant.update(payout_rate_variant_params)
      redirect_to @payout_rate_variant, notice: "Payout rate variant was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /payout_rate_variants/1
  def destroy
    @payout_rate_variant.destroy
    redirect_to payout_rate_variants_url, notice: "Payout rate variant was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payout_rate_variant
    @payout_rate_variant = PayoutRateVariant.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def payout_rate_variant_params
    params.require(:payout_rate_variant).permit(:payout_id, :earning_rate_id, :earning_type_id)
  end
end

horizonpwr-rails/app/helpers/payout_rate_variants_helper.rb
module PayoutRateVariantsHelper
end

horizonpwr-rails/app/views/payout_rate_variants/_filter.html.erb
<!-- filters -->
<div class="flex " data-controller="onClick">
  <div data-onClick-target="leftButton" class="flex-1 hidden " data-action="click->onClick#scrollLeft">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
    </svg>
  </div>
  <div data-controller="onScroll" data-onClick-target="filtersContainer" data-action="scroll->onScroll#scrollMove" class="float-left whitespace-nowrap overflow-x-auto scrollbar-hide w-full px-2">
    <%= link_to "All", payout_rate_variants_path(filter: 'all'), class:'' %>
    <% PayoutRateVariant.statuses.each do |status| -%>
    <%= link_to "#{status}", payout_rate_variants_path(filter: status), class:'' %>
    <% end %>
  </div>
  <div data-onClick-target="rightButton" class="flex-1" data-action="click->onClick#scrollRight">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
    </svg>
  </div>
</div>
<!-- end of filters -->

horizonpwr-rails/app/views/payout_rate_variants/_form.html.erb
<%= form_with(model: payout_rate_variant) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="form-group">
    <%= form.label :payout_id %>
    <%= form.text_field :payout_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :earning_rate_id %>
    <%= form.text_field :earning_rate_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :earning_type_id %>
    <%= form.text_field :earning_type_id, class: "form-control" %>
  </div>

  <div class="form-group flex justify-between">
    <%= form.button class: "btn btn-primary" %>

    <% if form.object.persisted? %>
      <%= link_to t("delete"), form.object, class: "btn btn-danger outline", method: :delete, data: { confirm: t("are_you_sure") } %>
    <% end %>
  </div>
<% end %>

horizonpwr-rails/app/views/payout_rate_variants/_search.html.erb
<div class="flex w-full shadow-lg rounded-md">
  <div class="w-3/4">
    <form action="/payout_rate_variants" accept-charset="UTF-8" method="get">
      <div class="relative">
        <input class="transition placeholder-gray-700 rounded-l-md border-r-0 border-gray-300 bg-white py-2 pr-4 pl-10 block w-full appearance-none leading-normal ds-input" placeholder="Search..." type="text" name="q" id="q" value="<%= params[:q] %>" required>
        <div class="pointer-events-none absolute inset-y-0 left-0 pl-4 flex items-center">
          <svg class="fill-current pointer-events-none text-gray-600 w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
          </svg>
        </div>
      </div>
    </form>
  </div>
  <div class="w-1/4">
    <%= render partial: "payout_rate_variants/sort" %>
  </div>
</div>

horizonpwr-rails/app/views/payout_rate_variants/_sort.html.erb
<div class="relative text-left" data-controller="dropdown" >
  <!-- sort dropdown -->
  <div data-action="click->dropdown#toggle click@window->dropdown#hide touch->dropdown#toggle touch@window->dropdown#hide" role="button" class="select-none relative rounded-l-none focus:outline-none rounded-r-md border-t border-b border-r border-gray-300 bg-white text-gray-700 hover:bg-gray-50" aria-label="Sort Menu">
    <p class="text-base leading-normal text-gray-500 absolute left-0 top-2">|</p>
    <div class="ml-1">
      <button type="button" class="inline-flex justify-center w-full p-2 hover:text-blue-500 focus:outline-none <%= 'font-semibold' if params[:sort].present? %>" id="menu-button" aria-expanded="true" aria-haspopup="true">
        sort
        <!-- Heroicon name: solid/chevron-down -->
        <svg class="h-5 w-5 pt-1 hover:text-blue-500 <%= 'font-semibold' if params[:sort].present? %>" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"/>
        </svg>
      </button>
    </div>
  </div>
  <!-- end of sort dropdown -->
  <!-- dropdown -->
  <div data-dropdown-target="menu" class="hidden origin-top-right absolute right-0 mt-2 w-36 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
    <div class="py-1" role="none">
              <div class="flex hover:bg-primary-100">
          <a href="#" class="text-gray-700 group flex items-center py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
            <%= sortable @payout_rate_variants, :payout_id, "Payout", class: "text-gray-700 mx-2 p-2 #{'font-semibold' if params[:sort].present? && params[:sort] == "payout_id"}" %>
          </a>
        </div>
              <div class="flex hover:bg-primary-100">
          <a href="#" class="text-gray-700 group flex items-center py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
            <%= sortable @payout_rate_variants, :earning_rate_id, "Earning rate", class: "text-gray-700 mx-2 p-2 #{'font-semibold' if params[:sort].present? && params[:sort] == "earning_rate_id"}" %>
          </a>
        </div>
              <div class="flex hover:bg-primary-100">
          <a href="#" class="text-gray-700 group flex items-center py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
            <%= sortable @payout_rate_variants, :earning_type_id, "Earning type", class: "text-gray-700 mx-2 p-2 #{'font-semibold' if params[:sort].present? && params[:sort] == "earning_type_id"}" %>
          </a>
        </div>
          </div>
  </div>
  <!-- end of dropdown -->
</div>

horizonpwr-rails/app/views/payout_rate_variants/edit.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-3xl mx-auto">
    <div class="flex justify-between items-center mb-4">
      <h1 class="h3"><%= t("shared.scaffold.edit.title", model: "Payout Rate Variant") %></h1>
      <%= link_to t("cancel"), @payout_rate_variant, class: "btn btn-link" %>
    </div>

    <div class="bg-white rounded shadow p-8">
      <%= render "form", payout_rate_variant: @payout_rate_variant %>
    </div>
  </div>
</div>

horizonpwr-rails/app/views/payout_rate_variants/index.html.erb
<div class="mx-auto my-4 px-1 md:px-2 lg:px-4">
<!--  <div class="flow-root lg:mb-4 <%#= 'hidden' if !@payout_rate_variants.any? %>">-->
    <%#= link_to t("shared.scaffold.new.title", model: "Payout Rate Variant"), new_payout_rate_variant_path, class: "btn btn-primary lg:hidden" %>
<!--  </div>-->
  <div class="flex-none flex-wrap-reverse lg:flex-wrap lg:flex items-center mb-4">
    <div class="w-full lg:w-1/4">
      <div class="flex justify-between">
        <h1 class="h3 mr-2">
          <%= link_to 'Payout Rate Variants', payout_rate_variants_path, class:"text-gray-900" %>
        </h1>
        <%#= link_to t("shared.scaffold.new.title", model: "Payout Rate Variant"), new_payout_rate_variant_path, class: "btn btn-primary lg:hidden" %>
      </div>
    </div>

    <% if @payout_rate_variants.any? %>
      <div class="w-full lg:w-1/2">
        <%= render partial: "payout_rate_variants/filter" %>
      </div>
      <div class="w-full lg:w-1/4">
        <%= render partial: "payout_rate_variants/search" %>
      </div>
    <div class="w-full mt-2 text-center text-sm <%= 'hidden' if !params[:filter].present? %>">
      Filtered by: <%= "'#{params[:filter]}'" %>
    </div>
    <% end %>
  </div>
  <div class="">
    <% if @payout_rate_variants.any? %>
      <div class="bg-white rounded shadow table-responsive">
        <table class="table">
          <thead>
            <tr>
                <th class="p-3 uppercase text-left text-xs"><%= sortable @payout_rate_variants, :payout_id, "Payout", class: "text-gray-700" %></th>
                <th class="p-3 uppercase text-left text-xs"><%= sortable @payout_rate_variants, :earning_rate_id, "Earning rate", class: "text-gray-700" %></th>
                <th class="p-3 uppercase text-left text-xs"><%= sortable @payout_rate_variants, :earning_type_id, "Earning type", class: "text-gray-700" %></th>
                <th class="p-3 uppercase text-left text-xs text-gray-700 w-20"><%= t("shared.scaffold.actions") %></th>
            </tr>
          </thead>

          <tbody>
          <% @payout_rate_variants.each do |payout_rate_variant| %>
            <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= payout_rate_variant.payout_id %></td>
                          <td class="p-3"><%= payout_rate_variant.earning_rate_id %></td>
                          <td class="p-3"><%= payout_rate_variant.earning_type_id %></td>
            
              <td>
                <%= link_to t("shared.scaffold.view"), payout_rate_variant, class: "btn btn-link no-underline" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

   <%= render "shared/custom_pagy" %>

    <% else %>
      <div class="bg-white rounded shadow flex flex-col items-center justify-between p-8 lg:flex-row">
        <%= image_tag "empty.svg", class: "mb-4 lg:w-1/2" %>
        <div class="flex-1 text-center">
          <p class="h3 mb-4">Create your first Payout Rate Variant</p>
          <%= link_to t("shared.scaffold.new.title", model: "Payout Rate Variant"), new_payout_rate_variant_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

horizonpwr-rails/app/views/payout_rate_variants/new.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-3xl mx-auto">
    <div class="flex justify-between items-center mb-4">
      <h1 class="h3"><%= t("shared.scaffold.new.title", model: "Payout Rate Variant") %></h1>
      <%= link_to t("cancel"), payout_rate_variants_path, class: "btn btn-link" %>
    </div>

    <div class="bg-white rounded shadow p-8">
      <%= render "form", payout_rate_variant: @payout_rate_variant %>
    </div>
  </div>
</div>

horizonpwr-rails/app/views/payout_rate_variants/show.html.erb
<div class="container mx-auto my-8 px-4">
  <div class="max-w-3xl mx-auto">
    <div class="flex justify-between items-center mb-4">
      <h1 class="h3"><%= link_to "Payout Rate Variants", payout_rate_variants_path %> > Payout Rate Variant #<%= @payout_rate_variant.id %></h1>
      <%= link_to t("edit"), edit_payout_rate_variant_path(@payout_rate_variant), class: "btn btn-link" %>
    </div>

    <div class="bg-white rounded shadow p-8">
            <div class="mb-4">
        <h5>Payout</h5>
        <%= @payout_rate_variant.payout %>
      </div>
            <div class="mb-4">
        <h5>Earning rate</h5>
        <%= @payout_rate_variant.earning_rate %>
      </div>
            <div class="mb-4">
        <h5>Earning type</h5>
        <%= @payout_rate_variant.earning_type %>
      </div>
          </div>
  </div>
</div>